# Project information
site_name: "CIPS @ NYIST Documents"
site_description: "Documentation for CIPS service maintenance"
site_author: " NYIST CIPS - Computer and Information Processing Society"
site_url: "https://docs.mirror.nyist.edu.cn/"

# Repository
repo_name: NYIST-CIPS/documents
repo_url: "https://github.com/NYIST-CIPS/documents"

# Copyright
copyright: 'Copyright &copy; 2023-2024 CIPS @ NYIST. <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>.'

# Configuration
theme:
  name: material
  language: en
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb-off-outline
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: green
      accent: green
      toggle:
        icon: material/lightbulb-on-outline
        name: Switch to light mode
  icon:
    logo: fontawesome/brands/linux
    repo: octicons/mark-github-16
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.sections
    - navigation.top

# Customization
extra:
  social:
    - icon: octicons/globe-16
      link: "https://cips.ustc.edu.cn/"
    - icon: octicons/mark-github-16
      link: "https://github.com/NYIST-CIPS"

# extra_css:
#   - https://101.ustclug.org/css/extra.css

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - markdown.extensions.def_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets:
      base_path: [docs/assets/]
  - pymdownx.superfences
  - pymdownx.tilde
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Workflow:
    - New Server Setup Checklist: "workflow/new-server.md"
    - Mirrors maintenance: "workflow/mirrors/maintenance.md"
  - Infrastructure:
    - SSL Certificates: "infrastructure/ssl.md"
    - Monitor: "infrastructure/monitor.md"
    - GitHub: infrastructure/github.md
    - Docker Hub: infrastructure/dockerhub.md
  - Services:
    - services/index.md
    - Mirrors:
      - services/mirrors/index.md
      - Current (kruby):
        - services/mirrors/kruby/index.md
        - Networking:
          - Interfaces: services/mirrors/kruby/networking/index.md
        - Repositories: services/mirrors/kruby/repos.md
      - Auxiliary (3):
        - services/mirrors/3/index.md
        - Networking: services/mirrors/3/networking.md
      - Auxiliary (nuclear):
        - services/mirrors/nuclear/index.md
        - Networking: services/mirrors/nuclear/networking.md
      - Auxiliary (delta): 
        - services/mirrors/delta/index.md
        - Networking: services/mirrors/delta/networking.md
      - Docker: "services/mirrors/docker.md"
      - IPMI: "services/mirrors/ipmi.md"
      - ZFS: "services/mirrors/zfs.md"
      - Services: services/mirrors/services.md
      - Monitoring: services/mirrors/monitor.md
      - Repo sync: "services/mirrors/kruby/repos.md"
    - GitLab: "services/gitlab.md"
    - PXE:
      - "services/pxe/index.md"
      - Images: "services/pxe/images.md"
      - LIIMS: "services/pxe/liims.md"
  - Common Issues:
    - Nginx: faq/nginx.md
    - systemd-timer: faq/systemd-timer.md
    - Docker: faq/docker.md
